sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: AKIDBOgAfBnR7nMcsbEgEduFauDUwT2kdbeZ
    access-key-secret: QycelyEwrkVGF8xkR6lMuQ5spoKvoprx
    bucket-name: demostudy-1325056457
    endpoint: cos.ap-nanjing.myqcloud.com
  redis:
    host: localhost
    port: 6379
    database: 10
    password: 1433223xixi
  wechat:
    appid: wx5017c4667ccf75e4
    secret: 4da071f3af11f2ee33af66eb8d9c8c89
    notify-url:  https://330f0ea1.r15.cpolar.top/notify/paySucess